### ISSUE TITLE
5 repos for one project

### ISSUE THREAD

**Issue by willr42** [holoiso-staging/issuetracker#10]
Why did this project split into 5 different repositories? What was wrong with one repo? And where is the source code located now? 

Is the intention for this project to no longer be open source? If so, the README should be updated to state that it is no longer `libre`.

**Comment by theVakhovskeIsTaken** [comment]
It was always 5-20 repositories in the past? I don't see a single problem, the build environment is there, postcopy is there, installer is there too

**Comment by willr42** [comment]
Where is the code?

**Comment by willr42** [comment]
I also do not understand the rationale behind splitting issues & releases off from the core repository. Can you explain that? The entire point is that there is one place for everything related to the project.
