### ISSUE TITLE
Feature request: Regenerate grub.cfg

### ISSUE THREAD

**Issue by vlolteanu** [holoiso-staging/issuetracker#12]
It would be nice to have a  "kosher" way of regenerating grub.conf, in case the kernel command line needs to be changed. Currently, `/boot` is read-only.

(My particular use case is that I have a flaky Bluetooth controller, and I need to pass `pci=nommconf` so my devices pair/connect consistently.)

**Comment by theVakhovskeIsTaken** [comment]
@vlolteanu sudo genquirks --grub_additional_options "pci=nommcomf" && steamos-readonly disable && holoiso-grub-update



this will persist thru updates

**Comment by vlolteanu** [comment]
Thanks!
