### ISSUE TITLE
[Operating system refuses to boot]

### ISSUE THREAD

**Issue by Govuin-vr** [holoiso-staging/issuetracker#14]
## Your Issue: System will not boot
```
When attempting to boot into the system it shows what I believe to be a distorted version of my OEM Computer logo
```

## Your device's full specs
```
CPU: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
GPU:  Nvidia GeForce RTX 3080 
```

## Installer used to install?
```
holoiso_beta_snapshot20240302.1307.27-INSTALLER-57-x86_64
```

## OS version (/etc/holoiso-release):
```
Cannot obtain this info
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
 Nope
```

## Did it work before?
```
*no*
```

**Comment by theVakhovskeIsTaken** [comment]
wrong installer, issue closed
