### ISSUE TITLE
Why no support for ntfs-3g?

### ISSUE THREAD

**Issue by annaclets** [holoiso-staging/issuetracker#16]
I successfully installed a dual-boot of the latest immutable holoiso version, but I can't use as additional storage my ntfs partitions which contain my steam games because support for ntfs-3g is not included in the kernel. Why? The previous non-immutable versions included ntfs-3g.

CPU: AMD Ryzen 9 7940HS
GPU: AMD Radeon 780M

holoiso_beta_snapshot20240302.1307.27-INSTALLER-47-x86_64.iso

**Comment by annaclets** [comment]
I'm trying to make do with the built-in ntfs3 driver, but it is so buggy and without fail, corrupts the ntfs partitions. Ntfs3 is simply not viable. Is there any way at all for me to manually add ntfs-3g to holoISO?

**Comment by theVakhovskeIsTaken** [comment]
ntfs3 has been fixed in new releases, give it a go.
