### ISSUE TITLE
Server Report

### ISSUE THREAD

**Issue by iero15** [holoiso-staging/issuetracker#18]
## Your Issue:
```
Servers for the main installer aren't working

**Comment by iero15** [comment]
https://cd2.holoiso.ru.eu.org/holoiso-installer/holoiso_beta_snapshot20240302.1307.27-INSTALLER-47-x86_64.iso

**Comment by iero15** [comment]
![image_2024-03-15_184531391](https://github.com/holoiso-staging/issuetracker/assets/147993864/08b47390-7634-4d37-8671-b17466299772)

**Comment by iero15** [comment]
![image_2024-03-15_184603775](https://github.com/holoiso-staging/issuetracker/assets/147993864/b22c0469-d1a5-414b-9bb3-083e0f7895ba)

**Comment by theVakhovskeIsTaken** [comment]
Replace `cd2` with `get`

**Comment by iero15** [comment]
https://github.com/holoiso-staging/issuetracker/assets/147993864/1bbf94b4-c313-490d-afe5-67c257d022c6

**Comment by iero15** [comment]
it doesn't work
