### ISSUE TITLE
Boot loop

### ISSUE THREAD

**Issue by CoolGames101** [holoiso-staging/issuetracker#2]
## Your Issue:
Boot looping
*type your problem here*
After I installed holoiso it started boot looping 

## Your device's full specs

CPU: Intel i7 12 gen
GPU: NVIDIA GTX 1080
```

## Installer used to install?
```
*EXAMPLE: holoiso_000000.iso*
```

## OS version (/etc/holoiso-release):
```
*contents of that file*
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
*Please put anything here if you tried to launch session separately*
```

## Did it work before?
```
*No
```

**Comment by sapkyy** [comment]
Same issue (?). Stuck on Loading Operating System

**Comment by theVakhovskeIsTaken** [comment]
Did you install the right one?
