### ISSUE TITLE
get.holoiso.ru.eu.org not resolving

### ISSUE THREAD

**Issue by eeeyrie** [holoiso-staging/issuetracker#21]
The official download links (on get.holoiso.ru.eu.org) don't work because they give a generic "Server Not Found" error.
This is most likely a server issue

**Comment by eeeyrie** [comment]
Seems like it now redirects to "dl.holoiso.ru.eu.org", but it still doesn't resolve for me

**Comment by st737** [comment]
same here :bowtie:

**Comment by eng1n88r** [comment]
Link from the Telegram to the [.iso](https://drive.google.com/file/d/1WA-91eQRb2mQBiD7OgqR7BLwFC_JTeq0/view?usp=drive_link) image.

**Comment by st737** [comment]
thank you :fishsticks:
