### ISSUE TITLE
Iso file dev_nv can't download

### ISSUE THREAD

**Issue by Nidalas10** [holoiso-staging/issuetracker#32]
## Your Issue:
```
I can't download iso dev_nv. It says site can't be reach.
File iso address:https://get.holoiso.ru.eu.org/holoiso-installer/dev_nv/holoiso_beta_snapshot20240122.2200.45-dev_nv-INSTALLER-20-x86_64.iso
```

**Comment by Nidalas10** [comment]
![Uploading Screenshot_2024-04-09-01-03-30-33_4641ebc0df1485bf6b47ebd018b5ee76.jpg…]()

**Comment by Nidalas10** [comment]
Anybody have a alternative link to download dev_nv holoiso?

**Comment by Govuin-vr** [comment]
I had the iso file and I can put it in a Google Drive where you can grab it Until the issue is fixed let me know if you'd want that

**Comment by Nidalas10** [comment]
> I had the iso file and I can put it in a Google Drive where you can grab it Until the issue is fixed let me know if you'd want that

Yes, I want it

**Comment by Nidalas10** [comment]
Can it be accelerated, provided the Google Drive download link

**Comment by Nidalas10** [comment]
It's been 2 days, where is the Google Drive link

**Comment by Govuin-vr** [comment]
sorry i took so long here you go https://drive.google.com/drive/folders/1fBRupuBPaxRxZuLY2vVJGnv65RfW0_Eu?usp=sharing

**Comment by Nidalas10** [comment]
Thank you

**Comment by Nidalas10** [comment]
Do I close this issue or not?

**Comment by Govuin-vr** [comment]
sure! I mean you do have the file now
