### ISSUE TITLE
Holo-Iso Install on laptop but doesnt boot[Report]

### ISSUE THREAD

**Issue by SelimGOZ** [holoiso-staging/issuetracker#42]
## Your Issue:
Helo-iso installs on Lenevo X1 Carbon 8th gen but doesnt boot
*type your problem here*
I can install HoloIso on my Lenevo X1 Carbon 8th gen but trying to boot it doesnt work and boots me straight to bios
```
## Your device's full specs
CPU: Intel core i7-10510U 1.80GHz
GPU: Intel(R) UHD Graphics (integrated)
RAM: 16 GB (soldered)
SSD: SAMSUNG MZVLB1T0HBLR-000L7
```

## Installer used to install?
```
holoiso_beta_snapshot20240325.1158.39-InstallerBuild-20240401131732-x86_64 (2).iso
```

## OS version (/etc/holoiso-release):
```
N/A (Don't Know)
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
Wouldn't boot so never could
```

## Did it work before?
```
no
```

**Comment by GuestSneezeOSDev** [comment]
is it dualbooting or erase disk? and what drive did you install it on sda (C:) or sdb (D:)

**Comment by SelimGOZ** [comment]
its erase disk and no sda for some reason it only said nvme0n1

**Comment by GuestSneezeOSDev** [comment]
nvme0n1 is a partition for the nvme drive I assumed you had an SSD drive you could reinstall windows and create a new partition (70 GB Minumum) and there will be a new option nvme0n1p2 if it still only has nvme0n1 you could try using the CLI version of the installer or use a similar copy

**Comment by Axedane** [comment]
I actually met that issue before! And there is a fix now! The 1.3 Update... IGpu haven`t been supported before.

**Comment by GuestSneezeOSDev** [comment]
why not try using other steamos distro's such as winesapos,bazzite,guestsneezeos?

**Comment by theVakhovskeIsTaken** [comment]
Made working after 1.3 on my i3-1005G1 (Ice Lake GT1)
Closing issue

**Comment by SelimGOZ** [comment]
eh im using a tweaked version of holoiso and its working for me now :p
