### ISSUE TITLE
HoloISO iso file can be installed to a VM,but the VM can't boot.

### ISSUE THREAD

**Issue by Marietto2008** [holoiso-staging/issuetracker#43]
Hello.

I'm trying to install and boot HoloIso as a bhyve VM on FreeBSD. This is how I tried to install it. The parameters that I've used are :

```
/usr/sbin/./bhyve-lin -S -c sockets=2,cores=2,threads=2 -m 4G -w -H -A \
-s 0,hostbridge \
-s 1,ahci-cd,/mnt/zroot2/zroot2/OS/Linux/holoiso_beta_snapshot20240325.1158.39-InstallerBuild-20240401131732-x86_64.iso,bootindex=1 \
-s 2,ahci-hd,/mnt/zroot-133/bhyve/img/Linux/holoiso.img \
-s 11,hda,play=/dev/dsp,rec=/dev/dsp \
-s 13,virtio-net,tap4 \
-s 14,virtio-9p,sharename=/ \
-s 29,fbuf,tcp=0.0.0.0:5904,w=1600,h=950,wait \
-s 30,xhci,tablet \
-s 31,lpc \
-l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI_CODE.fd \
vm0:4 < /dev/null & sleep 2 && vncviewer 0:4
```

The image has been installed correctly inside the img file,but then,when I tried to boot HoloISO from the image file using these parameters :

```
/usr/sbin/./bhyve-lin -S -c sockets=2,cores=2,threads=2 -m 4G -w -H -A \
-s 0,hostbridge \
-s 1,ahci-hd,/mnt/zroot-133/bhyve/img/Linux/holoiso.img \
-s 11,hda,play=/dev/dsp,rec=/dev/dsp \
-s 13,virtio-net,tap4 \
-s 14,virtio-9p,sharename=/ \
-s 29,fbuf,tcp=0.0.0.0:5904,w=1600,h=950,wait \
-s 30,xhci,tablet \
-s 31,lpc \
-l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI_CODE.fd \
vm0:4 < /dev/null & sleep 2 && vncviewer 0:4
```

bhyve reported this error :

![Istantanea_2024-05-27_18-00-51](https://github.com/HoloISO/issuetracker/assets/755339/afc76846-e76d-484b-a556-71628c104ae0)

so it won't boot.

On May 13, 2022,I've tried to boot an old ISO image of HoloISO and in that time I've been able to boot it :
 
https://forums.freebsd.org/threads/steamos-holo-archiso-on-freebsd-virtualized-with-bhyve-jupiter-controller-firmware-update-service-failed.85154/#post-567900

on that date I've used this ISO image :

`SteamOS_Holo-20220510_0636_amdgpu-x86_64.iso `

What changed in the while ? Why the 2022 iso image is able to boot but the 2024 iso image does not ?

**Comment by theVakhovskeIsTaken** [comment]
No support for VMs will be provided unless it's an instance with passed through GPU.
