### ISSUE TITLE
[Report] Switching to desktop mode doesn't work on Intel Arc GPU

### ISSUE THREAD

**Issue by Drelek** [holoiso-staging/issuetracker#48]
## Your Issue:
```
Xorg defaults to the xf86-video-intel driver, which is too old and does not support Intel Arc gpus.
As a result, switching to desktop mode results in a black screen.
```

## Your device's full specs
```
CPU: AMD Ryzen 5 5600X
GPU: Intel Arc A770
```

## Installer used to install?
```
holoiso_rel_snapshot20240603.0905.04-InstallerBuild-20240603104443-x86_64.iso
```

## OS version (/etc/holoiso-release):
```
IMAGE_ID="holoiso_rel_snapshot20240603.0905.04"
DS_TAG=snapshot20240603.0905.04
RELEASETYPE=rel
ISINTERNAL=no
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
N/A
```

## Did it work before?
```
Hasn't worked since I installed. Only tried this version of HoloISO.
```

Eventually I was able to fix this by switching to TTY2 (`ctrl + alt + f2`) and uninstalling the old driver with `sudo pacman -R xf86-video-intel`, thus forcing xorg to use the built-in modesetting driver. Aside from this issue, HoloISO has been working perfectly on my setup - I understand xf86-video-intel may be required for supporting older Intel iGPUs, but perhaps a future release could include xorg configuration to default the driver to modesetting for Intel Arc and newer Intel iGPUs?

**Comment by theVakhovskeIsTaken** [comment]
@Drelek I guess, I can take a look at it

**Comment by theVakhovskeIsTaken** [comment]
Issue will be fixed by next beta build, closing issue
