### ISSUE TITLE
[Report] Boot stop at boot messages

### ISSUE THREAD

**Issue by h0m3** [holoiso-staging/issuetracker#8]
## Your Issue:
```
After installing HoloISO I get to the boot messages and the system hangs, no keyboard shortcut works including ctrl+alt+f3 forcing a hard-reset on the system. 
```

## Your device's full specs
```
CPU: AMD Ryzen 5700X
GPU: AMD Radeon RX7700XT
```

## Installer used to install?
```
holoiso_beta_snapshot20240125.1712.26-INSTALLER-06-x86_64.iso
```

## OS version (/etc/holoiso-release):
```
Cannot read since I cannot boot into the system
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
Cannot since I cannot boot into the system
```

## Did it work before?
```
No, first installation
```

**Comment by theVakhovskeIsTaken** [comment]
@h0m3 7xxx GPUs aren't supported at that moment (I'll add it later)

**Comment by ADVAFTB** [comment]
> @h0m3 7xxx GPUs aren't supported at that moment (I'll add it later)

It’s not even worth believing, I don’t believe all Borsky holoiso not working for PC before, it worked right now, but it’s not like that, so if you want to use the system, install Windows or Linux and use the game mode on steam, this system sucks, as he did for his device 
I’ll tell you right away if you don’t know how to use a normal kernel

**Comment by theVakhovskeIsTaken** [comment]
Issue fixed.
