### ISSUE TITLE
Why cant i install on certain partitions anymore?

### ISSUE THREAD

**Issue by Minepool9** [holoiso-staging/issuetracker#9]
Old version of holo allowed you to install on any partition on any disk

Now i have to wipe my entire disk to install holo instead of just selecting a efi partition and a ext4 one

Come on. Fix that in the installer. I wanna be able to install the gosh darn operating system without thanos snapping my own drive.

**Comment by lee-chang** [comment]
+1

**Comment by boredpengu** [comment]
+1

important for initial testing before doubling down and wiping the entire drive

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/HoloISO/holoiso/issues/870#issuecomment-1895654808.


A guide to manually install will be available later

**Comment by L1keava** [comment]
+1 
I think I'm the only one who needs this XD
